exports.compareObjectWords = word => {
    return words[word]
}

const words = {
    "door": "door",
    "opening": "door",
    "exit": "door",
    "entrance": "door",
    "room": "room",
    "here": "room",
    "area": "room",
    "building": "room",
    "opening": "room",
    "enclosure": "room",
    "bedroom": "room",
    "lab": "room",
    "laboratory": "room",
    "closet": "room",
    "space": "room",
    "hall": "room",
    "hallway": "room",
    "pod": "pod",
    "pods": "pod",
    "lighter": "lighter",
    "left": "left",
    "right": "right",
    "art": "art",
    "frame": "art",
    "frames": "art",
    "painting": "art",
    "paintings": "art",
    "photo": "art",
    "photos": "art",
    "picture": "art",
    "pictures": "art",
    "package": "package",
    "box": "package",
    "bundle": "package",
    "bomb": "package",
    "explosive": "package",
    "blocker": "blocker",
    "barricade": "blocker",
    "wall": "blocker",
    "terminal": "terminal",
    "computer": "terminal",
    "screen": "terminal",
    "keyboard": "terminal"
}